/* frequency.js -- corpus frequency counts for new-card selection weighting.
 *
 * GENERATED by scripts/count_freq.py -- do not edit by hand.
 *
 * Source: UD_French-GSD + UD_French-Sequoia (all splits), written register,
 * hand-checked morphology. Counts are per (verb, tense) cell, summed across
 * person/number. Compound tenses are counted on the participle, with the
 * tense read off its aux:tense auxiliary; the auxiliary itself is not counted
 * as a use of avoir/etre. Only non-zero cells are stored; FREQ.count()
 * returns 0 for anything absent.
 *
 * Known caveats in the source data (kept as-is, not corrected for): it is
 * news, wiki and administrative prose, so the impératif and the 1st/2nd
 * persons are drastically undercounted relative to speech, and the passé
 * simple shows up in narrative/encyclopedic text more than in conversation.
 * Se lever is counted only where the parse marks the reflexive pronoun.
 */
var FREQ = (function () {
  var CELLS = {
    pres: { 'être': 4886, 'avoir': 608, 'pouvoir': 500, 'faire': 376, 'devoir': 328, 'aller': 147, 'prendre': 113, 'venir': 86, 'mettre': 79, 'vouloir': 76, 'savoir': 66, 'voir': 65, 'commencer': 63, 'connaître': 61, 'dire': 56, 'recevoir': 56, 'rendre': 54, 'tenir': 39, 'parler': 38, 'appeler': 34, 'écrire': 34, 'vivre': 31, 'mourir': 30, 'partir': 28, 'croire': 27, 'naître': 22, 'sortir': 22, 'attendre': 21, 'finir': 20, 'ouvrir': 20, 'envoyer': 11, 'manger': 11, 'payer': 11, 'acheter': 10, 'préférer': 8, 'conduire': 7, 'courir': 4, 'lire': 2, 'boire': 1, 'dormir': 1, 'se lever': 1 },
    imparf: { 'être': 573, 'avoir': 107, 'devoir': 58, 'pouvoir': 45, 'faire': 42, 'aller': 23, 'vouloir': 20, 'dire': 16, 'vivre': 13, 'tenir': 12, 'voir': 12, 'venir': 10, 'parler': 9, 'appeler': 8, 'connaître': 8, 'savoir': 8, 'recevoir': 7, 'rendre': 7, 'attendre': 6, 'croire': 6, 'prendre': 5, 'mettre': 4, 'écrire': 4, 'commencer': 3, 'sortir': 3, 'conduire': 2, 'envoyer': 2, 'lire': 2, 'partir': 2, 'dormir': 1, 'manger': 1, 'naître': 1, 'payer': 1 },
    passeSimple: { 'être': 172, 'faire': 54, 'prendre': 32, 'avoir': 23, 'recevoir': 16, 'voir': 12, 'écrire': 12, 'devoir': 11, 'mourir': 11, 'commencer': 10, 'connaître': 9, 'mettre': 9, 'pouvoir': 9, 'envoyer': 8, 'rendre': 7, 'sortir': 5, 'conduire': 3, 'naître': 3, 'tenir': 3, 'acheter': 2, 'finir': 2, 'partir': 2, 'venir': 2, 'vivre': 2, 'vouloir': 2, 'aller': 1, 'appeler': 1, 'attendre': 1, 'dire': 1, 'lire': 1, 'ouvrir': 1 },
    futur: { 'être': 108, 'faire': 47, 'avoir': 42, 'pouvoir': 39, 'devoir': 22, 'voir': 11, 'savoir': 7, 'dire': 6, 'mettre': 6, 'prendre': 6, 'recevoir': 6, 'tenir': 6, 'venir': 6, 'conduire': 5, 'ouvrir': 4, 'rendre': 4, 'commencer': 3, 'envoyer': 3, 'connaître': 2, 'finir': 2, 'lire': 2, 'sortir': 2, 'écrire': 2, 'aller': 1, 'dormir': 1, 'mourir': 1, 'parler': 1, 'préférer': 1, 'se lever': 1, 'vivre': 1 },
    cond: { 'pouvoir': 89, 'être': 69, 'devoir': 63, 'vouloir': 29, 'avoir': 18, 'faire': 5, 'venir': 4, 'dire': 3, 'croire': 2, 'mettre': 2, 'rendre': 2, 'voir': 2, 'aller': 1, 'connaître': 1, 'prendre': 1 },
    passeCompose: { 'avoir': 114, 'faire': 81, 'pouvoir': 54, 'prendre': 47, 'naître': 44, 'recevoir': 43, 'mettre': 39, 'voir': 31, 'commencer': 27, 'dire': 24, 'tenir': 23, 'aller': 20, 'connaître': 18, 'devoir': 18, 'rendre': 16, 'écrire': 16, 'conduire': 14, 'mourir': 12, 'ouvrir': 12, 'sortir': 12, 'vouloir': 12, 'appeler': 11, 'finir': 11, 'savoir': 11, 'acheter': 8, 'envoyer': 8, 'parler': 8, 'vivre': 7, 'être': 7, 'partir': 6, 'venir': 6, 'lire': 5, 'préférer': 4, 'payer': 3, 'manger': 2, 'se lever': 2, 'attendre': 1, 'dormir': 1 },
    pqp: { 'faire': 16, 'avoir': 6, 'pouvoir': 6, 'dire': 5, 'mettre': 5, 'acheter': 4, 'devoir': 4, 'prendre': 4, 'recevoir': 4, 'écrire': 4, 'naître': 3, 'rendre': 3, 'venir': 3, 'voir': 3, 'manger': 2, 'partir': 2, 'sortir': 2, 'vivre': 2, 'appeler': 1, 'commencer': 1, 'conduire': 1, 'envoyer': 1, 'lire': 1, 'parler': 1, 'se lever': 1 },
    passeAnt: { 'mettre': 1, 'recevoir': 1 },
    futAnt: { 'faire': 2, 'finir': 1, 'mettre': 1, 'pouvoir': 1 },
    condPasse: { 'pouvoir': 12, 'devoir': 10, 'avoir': 9, 'faire': 5, 'mettre': 3, 'recevoir': 3, 'dire': 2, 'être': 2, 'aller': 1, 'commencer': 1, 'finir': 1, 'mourir': 1, 'naître': 1, 'partir': 1, 'payer': 1, 'écrire': 1 },
    subjPres: { 'être': 93, 'pouvoir': 37, 'faire': 13, 'avoir': 10, 'prendre': 7, 'devoir': 2, 'parler': 2, 'recevoir': 2, 'rendre': 2, 'tenir': 2, 'venir': 2, 'vouloir': 2, 'acheter': 1, 'aller': 1, 'appeler': 1, 'connaître': 1, 'dire': 1, 'envoyer': 1, 'mettre': 1, 'payer': 1, 'savoir': 1, 'vivre': 1, 'voir': 1 },
    subjPasse: { 'avoir': 6, 'faire': 2, 'naître': 2, 'acheter': 1, 'mourir': 1, 'prendre': 1, 'rendre': 1, 'voir': 1, 'écrire': 1 },
    subjImparf: { 'avoir': 1 },
    subjPqp: {  },
    imperatif: { 'aller': 15, 'vouloir': 10, 'faire': 5, 'croire': 3, 'dire': 3, 'prendre': 3, 'attendre': 2, 'parler': 2, 'venir': 2, 'être': 2, 'acheter': 1, 'envoyer': 1, 'lire': 1, 'mettre': 1, 'ouvrir': 1, 'partir': 1, 'préférer': 1, 'savoir': 1 }
  };

  function count(verb, tense) {
    var row = CELLS[tense];
    return (row && row[verb]) || 0;
  }

  return { count: count, CELLS: CELLS };
})();

if (typeof module !== 'undefined' && module.exports) module.exports = FREQ;
